CREATE TABLE RECINTOS (
	COD_RECINTO varchar(255) NOT NULL PRIMARY KEY,
    NOMBRE varchar(255) NOT NULL,
    DIRECCION varchar(255) NOT NULL,
    CIUDAD varchar(255) NOT NULL,
    TELEFONO int(9) unsigned NOT NULL,
    HORARIO enum("HOR1","HOR2","HOR3") NOT NULL
    
);

CREATE TABLE ESPECTACULOS (
    COD_ESPECTACULO varchar(255) NOT NULL PRIMARY KEY,
    COD_RECINTO varchar(255) NOT NULL,
    ZONA varchar(255) NOT NULL,
    PRECIO INT(255) CHECK (PRECIO >0),
    FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO) on delete cascade on update cascade

);

CREATE TABLE PRECIOS_ESPECTACULOS (
    COD_ESPECTACULO varchar(255) NOT NULL,
	COD_RECINTO varchar(255) NOT NULL,
    ZONA varchar(255) NOT NULL,
    PRECIO INT(255) CHECK (PRECIO >0),
    PRIMARY KEY (COD_ESPECTACULO, COD_RECINTO),
    FOREIGN KEY (COD_ESPECTACULO) REFERENCES ESPECTACULOS(COD_ESPECTACULO) on delete cascade on update cascade,
    FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO) on delete cascade on update cascade
    
);

CREATE TABLE ZONAS_RECINTOS (
	COD_RECINTO varchar(255) NOT NULL PRIMARY KEY,
    ZONA varchar(255) NOT NULL,
    CAPACIDAD int(255) unsigned NOT NULL,
    FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO) on delete cascade on update cascade

);

CREATE TABLE ASIENTOS (
	COD_RECINTO varchar(255) NOT NULL PRIMARY KEY,
    ZONA varchar(255) NOT NULL,
	FILA varchar(255) NOT NULL,
    NUMERO int(255) unsigned NOT NULL,
    FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO) on delete cascade on update cascade
    
);

CREATE TABLE REPRESENTACIONES (
	COD_ESPECTACULO varchar(255) NOT NULL,
    COD_RECINTO varchar(255) NOT NULL,
    FECHA date NOT NULL,
    HORA time NOT NULL,
    PRIMARY KEY (COD_ESPECTACULO, COD_RECINTO),
    FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO) on delete cascade on update cascade,
    FOREIGN KEY (COD_ESPECTACULO) REFERENCES ESPECTACULOS(COD_ESPECTACULO) on delete cascade on update cascade

);

CREATE TABLE ESPECTADORES (
	DNI_CLIENTE varchar(9) NOT NULL PRIMARY KEY,
    NOMBRE varchar(255) NOT NULL,
    DIRECCION varchar(255) NOT NULL,
    TELEFONO int(9) unsigned NOT NULL,
    CIUDAD varchar(255) NOT NULL,
	NTARJETA int(16) unsigned NOT NULL

);

CREATE TABLE ENTRADAS (
	COD_ESPECTACULO varchar(255) NOT NULL,
	COD_RECINTO varchar(255) NOT NULL,
	DNI_CLIENTE varchar(9) NOT NULL,
	FECHA date NOT NULL,
	HORA time NOT NULL,
	FILA varchar(255) NOT NULL,
    NUMERO int(255) unsigned NOT NULL,
    ZONA varchar(255) NOT NULL,
    PRIMARY KEY (COD_ESPECTACULO, COD_RECINTO, DNI_CLIENTE),
    FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO) on delete cascade on update cascade,
    FOREIGN KEY (COD_ESPECTACULO) REFERENCES ESPECTACULOS(COD_ESPECTACULO) on delete cascade on update cascade,
    FOREIGN KEY (DNI_CLIENTE) REFERENCES ESPECTADORES(DNI_CLIENTE) on delete cascade on update cascade
    
);
