CREATE TABLE LOCALIDAD (
  COD_LOCALIDAD int(255) NOT NULL primary key AUTO_INCREMENT,
  NOMBRE varchar(255) NOT NULL 

);

CREATE TABLE PUB (
  COD_PUB varchar(255) NOT NULL primary key,
  NOMBRE varchar(255) NOT NULL ,
  LICENCIA_FISCAL varchar(255) NOT NULL,
  DOMICILIO varchar(255) NULL,
  FECHA_APERTURA date NOT NULL,
  HORARIO enum("HOR1","HOR2","HOR3") NOT NULL,
  COD_LOCALIDAD int(255) NOT NULL,
  FOREIGN KEY (COD_LOCALIDAD) REFERENCES LOCALIDAD(COD_LOCALIDAD)on delete cascade on update cascade

);

CREATE TABLE TITULAR (
  DNI_TITULAR varchar(9) NOT NULL primary key,
  NOMBRE varchar(255) NOT NULL ,
  DOMICILIO varchar(255) NULL,
  COD_PUB varchar(255) NOT NULL,
  FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB)on delete cascade on update cascade

);

CREATE TABLE EMPLEADO (
  DNI_EMPLEADO varchar(255) NOT NULL primary key,
  NOMBRE varchar(255) NOT NULL ,
  DOMICILIO varchar(255) NULL

);

CREATE TABLE EXISTENCIAS (
  COD_ARTICULO int(255) NOT NULL primary key AUTO_INCREMENT,
  NOMBRE varchar(255) NOT NULL ,
  CANTIDAD int(255) unsigned NOT NULL,
  PRECIO int(255) CHECK (PRECIO > 0 ),
  COD_PUB varchar(255) NOT NULL,
  FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB)on delete cascade on update cascade

);

CREATE TABLE PUB_EMPLEADO (
  COD_PUB varchar(255) NOT NULL,
  DNI_EMPLEADO varchar(9) NOT NULL,
  FUNCION enum("CAMARERO","SEGURIDAD","LIMPIEZA") NOT NULL,
  PRIMARY KEY (COD_PUB, DNI_EMPLEADO, FUNCION),
  FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB)on delete cascade on update cascade,
  FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO(DNI_EMPLEADO)on delete cascade on update cascade

);
